"""BC model training pipeline.

Trains an XGBoost multi-class classifier (100 joint-action classes) on
behavioral cloning data generated by expert self-play. Uses Optuna for
hyperparameter optimization with stratified k-fold CV and MLflow tracking.

Usage:
    uv run python -m src.tree_bc.optuna \
        --data-dir=data/BC --n-trials=50 --output-dir=src/models
"""

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

import joblib
import mlflow
import numpy as np
import numpy.typing as npt
import optuna
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from src.shared.s3 import sync_from_s3
from src.tree_bc.encoder import FEATURE_DIM

EXPERIMENT_NAME = "bc_action_training"
MODEL_DIR = Path(__file__).resolve().parent.parent / "models"
CV_FOLDS = 3
TEST_SIZE = 0.10
VAL_SIZE = 0.10
RANDOM_STATE = 42
EARLY_STOPPING_ROUNDS = 30
N_CLASSES = 100

EXPERT_SAMPLE_WEIGHTS: dict[str, float] = {
    "Greedy": 1.0,
    "caaaden": 0.75,
    "minimon": 0.5,
    "JJJ": 0.25,
    "dongimon": 0.15,
}


def load_bc_data(
    data_dir: Path, win_filter: bool = True
) -> tuple[
    npt.NDArray[np.float32],
    npt.NDArray[np.int32],
    npt.NDArray[np.bool_],
    npt.NDArray[np.float32],
]:
    """Load BC JSONL data into arrays for training.

    Args:
        data_dir: Directory containing bc_data_*.jsonl files.
        win_filter: If True, only keep records where won=True.

    Returns:
        Tuple of (features, actions, valid_masks, sample_weights).
        features: shape (N, FEATURE_DIM) float32.
        actions: shape (N,) int32, values 0-99.
        valid_masks: shape (N, N_CLASSES) bool.
        sample_weights: shape (N,) float32.

    Raises:
        FileNotFoundError: If no JSONL files found in data_dir.
    """
    jsonl_files = sorted(data_dir.glob("bc_data_*.jsonl"))
    if not jsonl_files:
        raise FileNotFoundError(f"No bc_data_*.jsonl files in {data_dir}")

    features_list: list[list[float]] = []
    actions_list: list[int] = []
    masks_list: list[list[bool]] = []
    weights_list: list[float] = []

    for jf in jsonl_files:
        with open(jf) as f:
            for line in f:
                row = json.loads(line)
                if win_filter and not row.get("won", True):
                    continue
                features_list.append(row["features"])
                actions_list.append(row["action_idx"])
                valid_indices = row["valid_actions"]
                mask = [False] * N_CLASSES
                for idx in valid_indices:
                    mask[idx] = True
                masks_list.append(mask)
                expert = row.get("expert", "JJJ")
                weights_list.append(EXPERT_SAMPLE_WEIGHTS.get(expert, 0.5))

    features = np.array(features_list, dtype=np.float32)
    actions = np.array(actions_list, dtype=np.int32)
    valid_masks = np.array(masks_list, dtype=bool)
    sample_weights = np.array(weights_list, dtype=np.float32)

    return features, actions, valid_masks, sample_weights


def _full_proba(
    model: XGBClassifier, X: npt.NDArray[np.float32]
) -> npt.NDArray[np.float64]:
    """Get predict_proba padded to full N_CLASSES width.

    XGBClassifier.predict_proba only returns columns for classes seen
    during fit. This maps them back to a (N, N_CLASSES) array using
    the model's learned classes_ attribute.

    Args:
        model: Fitted XGBClassifier.
        X: Feature matrix.

    Returns:
        Probability array of shape (N, N_CLASSES).
    """
    raw = model.predict_proba(X)
    if raw.shape[1] == N_CLASSES:
        return raw.astype(np.float64)
    full = np.zeros((raw.shape[0], N_CLASSES), dtype=np.float64)
    classes: npt.NDArray[np.int32] = model.classes_.astype(np.int32)
    full[:, classes] = raw
    return full


def _remap_labels(
    actions: npt.NDArray[np.int32],
) -> tuple[npt.NDArray[np.int32], npt.NDArray[np.int32]]:
    """Remap sparse action labels to consecutive 0..N-1 for XGBoost.

    Args:
        actions: Original action labels (may have gaps).

    Returns:
        Tuple of (remapped_actions, inverse_map) where inverse_map[i]
        gives the original action index for remapped class i.
    """
    unique_sorted = np.unique(actions)
    inverse_map = unique_sorted.astype(np.int32)
    mapping: npt.NDArray[np.int32] = np.full(N_CLASSES, -1, dtype=np.int32)
    for new_idx, orig_idx in enumerate(unique_sorted):
        mapping[orig_idx] = new_idx
    remapped = mapping[actions]
    return remapped, inverse_map


def valid_action_accuracy(
    y_true: npt.NDArray[np.int32],
    y_proba: npt.NDArray[np.float64],
    valid_masks: npt.NDArray[np.bool_],
) -> float:
    """Compute top-1 accuracy restricted to valid actions.

    Zeroes out probability mass on invalid actions before taking argmax.

    Args:
        y_true: True action indices, shape (N,).
        y_proba: Predicted probabilities, shape (N, N_CLASSES).
        valid_masks: Boolean masks, shape (N, N_CLASSES).

    Returns:
        Fraction of samples where masked argmax matches true action.
    """
    masked_proba = y_proba.copy()
    masked_proba[~valid_masks] = 0.0
    y_pred = masked_proba.argmax(axis=1)
    return float((y_pred == y_true).mean())


def split_data(
    features: npt.NDArray[np.float32],
    actions: npt.NDArray[np.int32],
    valid_masks: npt.NDArray[np.bool_],
    sample_weights: npt.NDArray[np.float32],
) -> tuple[
    npt.NDArray[np.float32],
    npt.NDArray[np.int32],
    npt.NDArray[np.bool_],
    npt.NDArray[np.float32],
    npt.NDArray[np.float32],
    npt.NDArray[np.int32],
    npt.NDArray[np.bool_],
    npt.NDArray[np.float32],
    npt.NDArray[np.float32],
    npt.NDArray[np.int32],
    npt.NDArray[np.bool_],
    npt.NDArray[np.float32],
]:
    """Split data into train/val/test sets stratified by action class.

    Args:
        features: Feature matrix, shape (N, D).
        actions: Action labels, shape (N,).
        valid_masks: Valid action masks, shape (N, 100).
        sample_weights: Per-sample weights, shape (N,).

    Returns:
        12-tuple: (X_train, y_train, m_train, w_train,
                   X_val, y_val, m_val, w_val,
                   X_test, y_test, m_test, w_test).
    """
    test_frac = TEST_SIZE
    val_frac = VAL_SIZE / (1.0 - TEST_SIZE)

    X_tr, X_test, y_tr, y_test, m_tr, m_test, w_tr, w_test = train_test_split(
        features, actions, valid_masks, sample_weights,
        test_size=test_frac, random_state=RANDOM_STATE, stratify=actions,
    )
    X_train, X_val, y_train, y_val, m_train, m_val, w_train, w_val = train_test_split(
        X_tr, y_tr, m_tr, w_tr,
        test_size=val_frac, random_state=RANDOM_STATE, stratify=y_tr,
    )

    return (
        X_train, y_train, m_train, w_train,
        X_val, y_val, m_val, w_val,
        X_test, y_test, m_test, w_test,
    )


def xgboost_objective(
    trial: optuna.Trial,
    X_train: npt.NDArray[np.float32],
    y_train: npt.NDArray[np.int32],
    m_train: npt.NDArray[np.bool_],
    w_train: npt.NDArray[np.float32],
    X_val: npt.NDArray[np.float32],
    y_val: npt.NDArray[np.int32],
    m_val: npt.NDArray[np.bool_],
) -> float:
    """Optuna objective: valid-action accuracy on held-out validation set.

    Args:
        trial: Optuna trial for hyperparameter suggestion.
        X_train: Training features.
        y_train: Training action labels.
        m_train: Training valid-action masks.
        w_train: Training sample weights.
        X_val: Validation features.
        y_val: Validation action labels.
        m_val: Validation valid-action masks.

    Returns:
        Valid-action accuracy on validation set.
    """
    params: dict[str, Any] = {
        "max_depth": trial.suggest_int("max_depth", 4, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 100, 600, step=50),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.4, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True),
        "objective": "multi:softprob",
        "random_state": RANDOM_STATE,
        "eval_metric": "mlogloss",
        "verbosity": 0,
        "early_stopping_rounds": EARLY_STOPPING_ROUNDS,
        "tree_method": "hist",
    }

    model = XGBClassifier(**params)
    model.fit(
        X_train, y_train,
        sample_weight=w_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )

    proba = model.predict_proba(X_val).astype(np.float64)
    acc = valid_action_accuracy(y_val, proba, m_val)
    return acc


def train(
    data_dir: Path,
    n_trials: int,
    output_dir: Path,
    study_db: Path | None,
    win_filter: bool,
) -> None:
    """Execute the full BC training pipeline.

    Loads data, runs Optuna hyperparameter search, retrains best model
    on train+val, evaluates on test set, saves artifacts.

    Args:
        data_dir: Directory containing bc_data_*.jsonl files.
        n_trials: Number of Optuna trials.
        output_dir: Directory for model artifacts and MLflow db.
        study_db: Path to Optuna study SQLite database (None for in-memory).
        win_filter: If True, only train on winning records.
    """
    print("=" * 60)
    print("BC Action Model Training (XGBoost 100-class)")
    print(f"  data_dir={data_dir}")
    print(f"  n_trials={n_trials}")
    print(f"  win_filter={win_filter}")
    print(f"  CV: single holdout val ({VAL_SIZE:.0%})")
    print(f"  early_stopping_rounds={EARLY_STOPPING_ROUNDS}")
    print("=" * 60)

    features, actions, valid_masks, sample_weights = load_bc_data(
        data_dir, win_filter=win_filter
    )
    print(f"\nLoaded {len(actions)} samples, {features.shape[1]} features")
    print(f"  Unique actions: {len(np.unique(actions))}/{N_CLASSES}")
    print(f"  Expert weight range: [{sample_weights.min():.2f}, {sample_weights.max():.2f}]")

    min_class_count = 3
    unique, counts = np.unique(actions, return_counts=True)
    rare_classes = set(unique[counts < min_class_count].tolist())
    if rare_classes:
        keep = np.array([a not in rare_classes for a in actions])
        features = features[keep]
        actions = actions[keep]
        valid_masks = valid_masks[keep]
        sample_weights = sample_weights[keep]
        print(f"  Dropped {len(rare_classes)} rare classes (<{min_class_count} samples): {sorted(rare_classes)}")
        print(f"  Remaining: {len(actions)} samples, {len(np.unique(actions))} classes")

    actions, inverse_map = _remap_labels(actions)
    n_present = len(inverse_map)
    print(f"  Remapped to {n_present} consecutive classes")

    remapped_masks: npt.NDArray[np.bool_] = np.zeros((len(actions), n_present), dtype=bool)
    for new_idx in range(n_present):
        orig_idx = inverse_map[new_idx]
        remapped_masks[:, new_idx] = valid_masks[:, orig_idx]
    valid_masks = remapped_masks

    (
        X_train, y_train, m_train, w_train,
        X_val, y_val, m_val, _w_val,
        X_test, y_test, m_test, _w_test,
    ) = split_data(features, actions, valid_masks, sample_weights)

    print(f"  Train: {len(y_train)} | Val: {len(y_val)} | Test: {len(y_test)}")

    output_dir.mkdir(parents=True, exist_ok=True)

    mlflow.set_tracking_uri(f"sqlite:///{(output_dir / 'mlflow_bc.db').resolve()}")
    mlflow.set_experiment(EXPERIMENT_NAME)

    storage = f"sqlite:///{study_db.resolve()}" if study_db else None
    study_name = "bc_xgboost"

    study = optuna.create_study(
        study_name=study_name,
        storage=storage,
        direction="maximize",
        load_if_exists=True,
    )

    print(f"\nRunning Optuna ({n_trials} trials)...")
    t0 = time.perf_counter()

    study.optimize(
        lambda trial: xgboost_objective(
            trial, X_train, y_train, m_train, w_train, X_val, y_val, m_val
        ),
        n_trials=n_trials,
        show_progress_bar=True,
    )

    optuna_time = time.perf_counter() - t0
    print(f"\nOptuna complete in {optuna_time:.1f}s")
    print(f"  Best trial: #{study.best_trial.number}")
    print(f"  Best val accuracy: {study.best_value:.4f}")
    print(f"  Best params: {study.best_params}")

    best_params: dict[str, Any] = {
        **study.best_params,
        "objective": "multi:softprob",
        "random_state": RANDOM_STATE,
        "eval_metric": "mlogloss",
        "verbosity": 0,
        "early_stopping_rounds": EARLY_STOPPING_ROUNDS,
        "tree_method": "hist",
    }

    print("\nRetraining best model on train+val...")
    X_full = np.concatenate([X_train, X_val])
    y_full = np.concatenate([y_train, y_val])
    w_full = np.concatenate([w_train, _w_val])

    final_model = XGBClassifier(**best_params)
    final_model.fit(
        X_full, y_full,
        sample_weight=w_full,
        eval_set=[(X_test, y_test)],
        verbose=False,
    )

    test_proba = final_model.predict_proba(X_test).astype(np.float64)
    test_acc = valid_action_accuracy(y_test, test_proba, m_test)
    train_proba = final_model.predict_proba(X_train).astype(np.float64)
    train_acc = valid_action_accuracy(y_train, train_proba, m_train)

    print(f"\n  Train accuracy (valid-masked): {train_acc:.4f}")
    print(f"  Test accuracy (valid-masked):  {test_acc:.4f}")

    with mlflow.start_run(run_name=f"bc_xgboost_{time.strftime('%Y%m%d_%H%M%S')}"):
        mlflow.log_params(study.best_params)
        mlflow.log_metric("val_accuracy", study.best_value)
        mlflow.log_metric("test_accuracy", test_acc)
        mlflow.log_metric("train_accuracy", train_acc)
        mlflow.log_metric("n_samples", len(actions))
        mlflow.log_metric("optuna_time_s", optuna_time)

    model_path = output_dir / "bc_xgboost_model.joblib"
    joblib.dump({"model": final_model, "inverse_map": inverse_map}, model_path)

    meta = {
        "model_type": "xgboost_multiclass",
        "n_classes": N_CLASSES,
        "feature_dim": FEATURE_DIM,
        "test_accuracy": test_acc,
        "train_accuracy": train_acc,
        "val_accuracy": study.best_value,
        "best_trial": study.best_trial.number,
        "best_params": study.best_params,
        "n_samples": int(len(actions)),
        "n_trials": n_trials,
        "win_filter": win_filter,
        "expert_weights": EXPERT_SAMPLE_WEIGHTS,
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    meta_path = output_dir / "bc_champion_meta.json"
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)

    print(f"\n  Model saved: {model_path}")
    print(f"  Metadata saved: {meta_path}")
    print("=" * 60)


def main() -> None:
    """CLI entry point for BC model training."""
    parser = argparse.ArgumentParser(description="Train BC action prediction model")
    parser.add_argument(
        "--data-dir", type=Path, default=Path("data/BC"),
        help="Directory containing bc_data_*.jsonl files",
    )
    parser.add_argument(
        "--n-trials", type=int, default=50,
        help="Number of Optuna trials (default: 50)",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=MODEL_DIR,
        help="Output directory for model artifacts",
    )
    parser.add_argument(
        "--study-db", type=Path, default=None,
        help="Optuna study SQLite path (default: in-memory)",
    )
    parser.add_argument(
        "--no-win-filter", action="store_true",
        help="Include losing records in training",
    )
    parser.add_argument(
        "--s3-bucket", type=str, default="",
        help="S3 bucket to sync training data from (skipped if empty)",
    )
    parser.add_argument(
        "--s3-prefix", type=str, default="data_BC/",
        help="S3 key prefix to sync into --data-dir (default: data_BC/)",
    )
    args = parser.parse_args()

    if args.s3_bucket:
        n = sync_from_s3(args.data_dir, args.s3_prefix, args.s3_bucket)
        print(f"Synced {n} files from s3://{args.s3_bucket}/{args.s3_prefix} to {args.data_dir}")

    train(
        data_dir=args.data_dir,
        n_trials=args.n_trials,
        output_dir=args.output_dir,
        study_db=args.study_db,
        win_filter=not args.no_win_filter,
    )


if __name__ == "__main__":
    main()
