w_base_score_a: 0.1057
w_base_score_b: 0.1436
w_env_synergy: 0.049
w_focus_fire: 0.4566
w_lookahead: 0.4949
w_off_def_support: 0.1357
w_setup_synergy: 0.0819
w_status_burn: 37.0473
w_status_para: 6.2412
w_status_poison: 74.0548
w_status_sleep: 64.7144
w_status_toxic: 13.0913
w_survival_impact: 0.0286
w_target_priority: 0.0169
