w_base_score: 0.2653
w_env_synergy: 0.205
w_focus_fire: 0.9086
w_off_def_support: 0.6978
w_setup_synergy: 0.7538
w_status_burn: 62.3448
w_status_para: 14.7879
w_status_poison: 12.9586
w_status_sleep: 70.4767
w_status_toxic: 37.8118
w_survival_impact: 0.8483
w_target_priority: 0.6992
