w_base_score_a: 0.0506
w_base_score_b: 0.2245
w_env_synergy: 0.0292
w_focus_fire: 0.3757
w_lookahead: 0.2248
w_off_def_support: 0.1745
w_setup_synergy: 0.1949
w_status_burn: 63.5139
w_status_para: 20.3508
w_status_poison: 65.8773
w_status_sleep: 51.486
w_status_toxic: 68.8008
w_survival_impact: 0.0618
w_target_priority: 0.2388
