ga_coverage: 0.2058
ga_coverage_balance: 0.1039
ga_defence: 0.0819
ga_role_diversity: 0.0752
ga_stat_diversity: 0.2744
ga_viability: 0.2588
w_dmg: 0.168
w_speed: 0.2763
w_speed_syn: 0.0846
w_stat: 0.0312
w_stat_syn: 0.3316
w_util: 0.1083
