ga_coverage: 0.0267
ga_coverage_balance: 0.0356
ga_defence: 0.0384
ga_role_diversity: 0.0352
ga_stat_diversity: 0.418
ga_viability: 0.446
w_dmg: 0.0352
w_speed: 0.063
w_speed_syn: 0.224
w_stat: 0.1487
w_stat_syn: 0.334
w_util: 0.195
